// Mocks generated by Mockito 5.4.6 from annotations
// in moveup_flutter/test/features/tests/catalog/data/repositories/tests_catalog_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:moveup_flutter/core/utils/logger/app_logger.dart' as _i6;
import 'package:moveup_flutter/features/tests/attempt/data/dto/complete_guest_test_request_dto.dart'
    as _i10;
import 'package:moveup_flutter/features/tests/attempt/data/dto/complete_guest_test_response_dto.dart'
    as _i5;
import 'package:moveup_flutter/features/tests/attempt/data/dto/save_guest_test_result_request_dto.dart'
    as _i9;
import 'package:moveup_flutter/features/tests/attempt/data/dto/save_guest_test_result_response_dto.dart'
    as _i4;
import 'package:moveup_flutter/features/tests/attempt/data/dto/start_guest_test_response_dto.dart'
    as _i3;
import 'package:moveup_flutter/features/tests/catalog/data/dto/testings_response_dto.dart'
    as _i2;
import 'package:moveup_flutter/features/tests/data/remote/tests_api_client.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTestingsResponseDto_0 extends _i1.SmartFake
    implements _i2.TestingsResponseDto {
  _FakeTestingsResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStartGuestTestResponseDto_1 extends _i1.SmartFake
    implements _i3.StartGuestTestResponseDto {
  _FakeStartGuestTestResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveGuestTestResultResponseDto_2 extends _i1.SmartFake
    implements _i4.SaveGuestTestResultResponseDto {
  _FakeSaveGuestTestResultResponseDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeCompleteGuestTestResponseDto_3 extends _i1.SmartFake
    implements _i5.CompleteGuestTestResponseDto {
  _FakeCompleteGuestTestResponseDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i6.AppLogger {
  @override
  void t(String? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#t, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void d(String? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#d, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void i(String? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#i, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void w(String? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#w, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void e(String? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#e, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void f(String? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#f, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TestsApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestsApiClient extends _i1.Mock implements _i7.TestsApiClient {
  @override
  _i8.Future<_i2.TestingsResponseDto> getTestings() =>
      (super.noSuchMethod(
            Invocation.method(#getTestings, []),
            returnValue: _i8.Future<_i2.TestingsResponseDto>.value(
              _FakeTestingsResponseDto_0(
                this,
                Invocation.method(#getTestings, []),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i2.TestingsResponseDto>.value(
                  _FakeTestingsResponseDto_0(
                    this,
                    Invocation.method(#getTestings, []),
                  ),
                ),
          )
          as _i8.Future<_i2.TestingsResponseDto>);

  @override
  _i8.Future<_i3.StartGuestTestResponseDto> startGuestTest(int? testingId) =>
      (super.noSuchMethod(
            Invocation.method(#startGuestTest, [testingId]),
            returnValue: _i8.Future<_i3.StartGuestTestResponseDto>.value(
              _FakeStartGuestTestResponseDto_1(
                this,
                Invocation.method(#startGuestTest, [testingId]),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i3.StartGuestTestResponseDto>.value(
                  _FakeStartGuestTestResponseDto_1(
                    this,
                    Invocation.method(#startGuestTest, [testingId]),
                  ),
                ),
          )
          as _i8.Future<_i3.StartGuestTestResponseDto>);

  @override
  _i8.Future<_i4.SaveGuestTestResultResponseDto> saveGuestTestResult(
    String? attemptId,
    _i9.SaveGuestTestResultRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveGuestTestResult, [attemptId, request]),
            returnValue: _i8.Future<_i4.SaveGuestTestResultResponseDto>.value(
              _FakeSaveGuestTestResultResponseDto_2(
                this,
                Invocation.method(#saveGuestTestResult, [attemptId, request]),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i4.SaveGuestTestResultResponseDto>.value(
                  _FakeSaveGuestTestResultResponseDto_2(
                    this,
                    Invocation.method(#saveGuestTestResult, [
                      attemptId,
                      request,
                    ]),
                  ),
                ),
          )
          as _i8.Future<_i4.SaveGuestTestResultResponseDto>);

  @override
  _i8.Future<_i5.CompleteGuestTestResponseDto> completeGuestTest(
    String? attemptId,
    _i10.CompleteGuestTestRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#completeGuestTest, [attemptId, request]),
            returnValue: _i8.Future<_i5.CompleteGuestTestResponseDto>.value(
              _FakeCompleteGuestTestResponseDto_3(
                this,
                Invocation.method(#completeGuestTest, [attemptId, request]),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i5.CompleteGuestTestResponseDto>.value(
                  _FakeCompleteGuestTestResponseDto_3(
                    this,
                    Invocation.method(#completeGuestTest, [attemptId, request]),
                  ),
                ),
          )
          as _i8.Future<_i5.CompleteGuestTestResponseDto>);
}
