// Mocks generated by Mockito 5.4.6 from annotations
// in moveup_flutter/test/features/tests/attempt/presentation/cubits/test_attempt_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:moveup_flutter/core/failures/feature/tests/tests_failure.dart'
    as _i6;
import 'package:moveup_flutter/core/result/result.dart' as _i4;
import 'package:moveup_flutter/features/tests/attempt/domain/entities/completed_test_attempt.dart'
    as _i9;
import 'package:moveup_flutter/features/tests/attempt/domain/entities/test_attempt_result.dart'
    as _i8;
import 'package:moveup_flutter/features/tests/attempt/domain/entities/test_attempt_start.dart'
    as _i5;
import 'package:moveup_flutter/features/tests/attempt/domain/repositories/test_attempt_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TestAttemptRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestAttemptRepository extends _i1.Mock
    implements _i2.TestAttemptRepository {
  @override
  _i3.Future<_i4.Result<_i5.TestAttemptStart, _i6.TestsFailure>> startTest(
    int? testingId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startTest, [testingId]),
            returnValue:
                _i3.Future<
                  _i4.Result<_i5.TestAttemptStart, _i6.TestsFailure>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i5.TestAttemptStart, _i6.TestsFailure>
                  >(this, Invocation.method(#startTest, [testingId])),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i4.Result<_i5.TestAttemptStart, _i6.TestsFailure>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i5.TestAttemptStart, _i6.TestsFailure>
                  >(this, Invocation.method(#startTest, [testingId])),
                ),
          )
          as _i3.Future<_i4.Result<_i5.TestAttemptStart, _i6.TestsFailure>>);

  @override
  _i3.Future<_i4.Result<_i8.TestAttemptResult, _i6.TestsFailure>> saveResult({
    required String? attemptId,
    required int? testingExerciseId,
    required int? resultValue,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveResult, [], {
              #attemptId: attemptId,
              #testingExerciseId: testingExerciseId,
              #resultValue: resultValue,
            }),
            returnValue:
                _i3.Future<
                  _i4.Result<_i8.TestAttemptResult, _i6.TestsFailure>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i8.TestAttemptResult, _i6.TestsFailure>
                  >(
                    this,
                    Invocation.method(#saveResult, [], {
                      #attemptId: attemptId,
                      #testingExerciseId: testingExerciseId,
                      #resultValue: resultValue,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i4.Result<_i8.TestAttemptResult, _i6.TestsFailure>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i8.TestAttemptResult, _i6.TestsFailure>
                  >(
                    this,
                    Invocation.method(#saveResult, [], {
                      #attemptId: attemptId,
                      #testingExerciseId: testingExerciseId,
                      #resultValue: resultValue,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i8.TestAttemptResult, _i6.TestsFailure>>);

  @override
  _i3.Future<_i4.Result<_i9.CompletedTestAttempt, _i6.TestsFailure>>
  completeTest({required String? attemptId, required int? pulse}) =>
      (super.noSuchMethod(
            Invocation.method(#completeTest, [], {
              #attemptId: attemptId,
              #pulse: pulse,
            }),
            returnValue:
                _i3.Future<
                  _i4.Result<_i9.CompletedTestAttempt, _i6.TestsFailure>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i9.CompletedTestAttempt, _i6.TestsFailure>
                  >(
                    this,
                    Invocation.method(#completeTest, [], {
                      #attemptId: attemptId,
                      #pulse: pulse,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i4.Result<_i9.CompletedTestAttempt, _i6.TestsFailure>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i9.CompletedTestAttempt, _i6.TestsFailure>
                  >(
                    this,
                    Invocation.method(#completeTest, [], {
                      #attemptId: attemptId,
                      #pulse: pulse,
                    }),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Result<_i9.CompletedTestAttempt, _i6.TestsFailure>
          >);
}
